# Generated by Django 3.0.1 on 2020-06-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='lane', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_address',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_city',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_state',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
