# Generated by Django 3.0.3 on 2020-06-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_table', '0004_student_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
    ]
