# Generated by Django 3.0.3 on 2020-06-04 09:49

from django.db import migrations
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student_table', '0005_remove_student_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
