# Generated by Django 3.0.3 on 2020-06-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_table', '0006_student_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ref_code',
            field=models.CharField(default='000', max_length=20),
        ),
    ]
