# Generated by Django 3.0.1 on 2020-06-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_table', '0007_auto_20200604_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='olmpaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('questions', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
