# Generated by Django 3.0.1 on 2020-06-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_table', '0008_olmpaid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='olmpaid',
            new_name='Olympiad',
        ),
    ]
