# Generated by Django 3.0.1 on 2020-06-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_table', '0009_auto_20200607_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
