# Generated by Django 3.0.1 on 2020-06-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_table', '0010_auto_20200608_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='rupees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
