# Generated by Django 3.0.1 on 2020-06-08 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_table', '0014_auto_20200608_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='student',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
